### ISSUE TITLE
Conforming `Real` to `Differentiable`

### ISSUE THREAD

**Issue by stephentyrone** [apple/swift-numerics#113]
As of https://github.com/apple/swift-numerics/pull/111, `Complex` now conforms to `Differentiable` if the underlying `RealType` does:
```swift
#if canImport(_Differentiation)
import _Differentiation

extension Complex: Differentiable
where RealType: Differentiable, RealType.TangentVector == RealType {
  public typealias TangentVector = Self
}
```

After some offline discussion with @rxwei, I'm considering the merits of making `Real` refine `Differentiable`:
```swift
#if canImport(_Differentiation)
public protocol Real: FloatingPoint, RealFunctions, AlgebraicField,
                      Differentiable where TangentVector == Self {
}
#else
public protocol Real: FloatingPoint, RealFunctions, AlgebraicField {
}
#endif
```

This would simplify the conformance for `Complex` by making it unconditional:
```swift
#if canImport(_Differentiation)
import _Differentiation

extension Complex: Differentiable {
  public typealias TangentVector = Self
}
```
and make `Real` more powerful itself, and so simplify a number of use sites somewhat. But it would imply a modest burden for any third-party types conforming to `Real`, because it does increase the API surface. I *think* that this trade-off makes sense, but I'd like to get people's feedback before adding the conformance.

It's also slightly weird to have a conformance that depends on availability of a module. Because Swift Numerics is not stable, and is distributed as source, this shouldn't pose a significant problem, but we might be painting ourselves into a corner w.r.t. possibly moving `Real` into the standard library at some future point. Language changes may make this less of an issue by that time, but we can't necessarily depend on that.

Thanks in advance!

**Comment by stephentyrone** [comment]
Tagging @NevinBR and @xwu, who are more likely to be effected by this if we do it than most people. (Xiaodi, I know you have a lot going on these days, so no need to reply unless you want a diversion.)

**Comment by NevinBR** [comment]
Is there any way to make this all live in a separate overlay module, eg. `DifferentiableNumerics`, which people can import if they want?

**Comment by rxwei** [comment]
> Is there any way to make this all live in a separate overlay module, eg. `DifferentiableNumerics`, which people can import if they want?

It is technically possible to add derivatives and `Differentiable` conformances retroactively, but retroactive refinement isn't possible so we would not be able to achieve the benefits of making `Real` refine `Differentiable`.

**Comment by stephentyrone** [comment]
What @rxwei said. The closest we could come with the language we have today would be to add a DifferentiableReal protocol.

It may be possible to put the refinement in a separate module at some future point, but I really can’t speculate on when that might be.

**Comment by kylemacomber** [comment]
If we get the fixes to typechecker performance and shadowing rules that allow us to incorporate Real into the Standard Library, but not any kind of retroactive protocol refinement... where does that leave us if we go in this direction?

**Comment by stephentyrone** [comment]
@kylemacomber In the worst case scenario you describe, we would drop the `Differentiable` refinement for Real in the standard library, and add a `DifferentiableReal` protocol in the _Differentiation module that's just `Real & Differentiable`. Anyone using the conformance would need to update the constraint in their code to use `DifferentiableReal` instead. That's a Source and ABI break, but the swift numerics Real module isn't resilient, and isn't source-stable, so clients have to expect such changes (even though we try to keep them to a minimum).

**Comment by stephentyrone** [comment]
Tagging @jckarter, who can maybe provide more context around any ABI issues we could run into if we do this.

**Comment by jckarter** [comment]
Have we implemented the ability to add retroactive refinements without breaking ABI yet? cc @slavapestov

**Comment by stephentyrone** [comment]
Ping @slavapestov

**Comment by slavapestov** [comment]
Unfortunately this change would be an ABI break. We do not allow retroactively adding new inherited protocols.

**Comment by rxwei** [comment]
> Unfortunately this change would be an ABI break. We do not allow retroactively adding new inherited protocols.

Does the ABI have space for this to be implemented in the future?

**Comment by stephentyrone** [comment]
Closing this for now.
