### ISSUE TITLE
Add copysign function

### ISSUE THREAD

**Issue by vliegeois** [apple/swift-numerics#130]
Would it make sense to add a copysign generic function for all Real?

Thank you

Vincent

**Comment by xwu** [comment]
Hi @vliegeois. The copysign function in Swift is named [`init(signOf:magnitudeOf:)`](https://developer.apple.com/documentation/swift/floatingpoint/1849294-init), and it is a protocol requirement of `FloatingPoint`.

**Comment by vliegeois** [comment]
Indeed. Thanks for the tip 👍
