### ISSUE TITLE
0.0.7 Broke Web Assembly

### ISSUE THREAD

**Issue by SDGGiesbrecht** [apple/swift-numerics#147]
I tried to update from 0.0.6 to 0.0.7, but it broke the web assembly build.

```swift
In file included from [...]/.build/checkouts/swift-numerics/Sources/_NumericsShims/_NumericsShims.c:19:
[...]/.build/checkouts/swift-numerics/Sources/_NumericsShims/include/_NumericsShims.h:387:42: error: _Float16 is not supported on this target
HEADER_SHIM _Float16 _numerics_muladdf16(_Float16 a, _Float16 b, _Float16 c) {
                                         ^
```

**Comment by stephentyrone** [comment]
Thanks, I'll take a look.

**Comment by SDGGiesbrecht** [comment]
Actually, yes, web assembly was just the first platform that my CI got to. All jobs were using Swift 5.2.4 unless otherwise specified:

- macOS, tvOS, iOS and watchOS succeeded.
- Windows (5.2.1), web (snapshot circa 5.2.1), CentOS, Ubuntu, Android (5.2.1) and Amazon Linux fail with the error message above.

**Comment by SDGGiesbrecht** [comment]
Full CI logs are [here](https://github.com/SDGGiesbrecht/SDGCornerstone/pull/371/checks?check_run_id=1024138790) in case there is other context information you want to fish out.

**Comment by stephentyrone** [comment]
Hi, since this was reported very quickly (thanks!), I simply updated the 0.0.7 tag. It should be resolved now if you get a fresh copy.

**Comment by SDGGiesbrecht** [comment]
I relaunched the CI jobs, you can watch them churn [here](https://github.com/SDGGiesbrecht/SDGCornerstone/pull/371/checks?check_run_id=1024260134).

**Comment by SDGGiesbrecht** [comment]
And again after forcing the pins to refresh [here](https://github.com/SDGGiesbrecht/SDGCornerstone/runs/1024272814). (I’m not sure what SwiftPM actually fetches when `Package.resolved` contains a version and revision that don’t match.)

**Comment by stephentyrone** [comment]
Yeah, I expect a few people will have some transient hassles from shifting the tag, but it seemed like the cleaner quick fix.

**Comment by SDGGiesbrecht** [comment]
The web job is now failing at a later point, but that one isn’t really `swift-numeric`’s fault, I don’t think. The snapshot in use is between 5.2 and 5.3, so I don’t think the [`#if swift(>=5.3)`](https://github.com/apple/swift-numerics/blob/3d7462a834b58b10b1af4b1a1e0eeb784835681b/Sources/RealModule/Float16%2BReal.swift#L12) is doing what it is supposed to. I think the toolchain considers itself 5.3 but doesn’t have `Float16` in the standard library yet. From what I can see in [`FloatingPointTypes.swift.gyb`](https://github.com/apple/swift/blob/103961a7d5f8853ac518f4d8151de0f5b64d8ccf/stdlib/public/core/FloatingPointTypes.swift.gyb), only `Float80` has platform restrictions, so I think the real 5.3 or a newer snapshot ought to actually contain `Float16` on WASI.

The other platforms are all passing now, so I’ll close this.

**Comment by SDGGiesbrecht** [comment]
Oh, and thanks for the quick fix!

**Comment by stephentyrone** [comment]
Yeah, I agree with your take on the web issue. Hopefully that will flush out relatively soon.
