### ISSUE TITLE
Implicit assumptions that Complex.RealType : BinaryFloatingPoint

### ISSUE THREAD

**Issue by NevinBR** [apple/swift-numerics#167]
`Complex.RealType` is constrained to `FloatingPoint` (among other things), but not `BinaryFloatingPoint`. However, some of the comment text in ComplexModule/ElementaryFunctions.swift seems to implicitly assume binary-ness of `RealType`:

> [a may be as small as 1/4, so we could lose a single bit to rounding](https://github.com/apple/swift-numerics/blob/4a2cbc186b1f8cbbc1ace12cef43d65784b2559e/Sources/ComplexModule/ElementaryFunctions.swift#L314-L317)

> [on this portion of the circle 1+x is always exact by Sterbenz' lemma](https://github.com/apple/swift-numerics/blob/4a2cbc186b1f8cbbc1ace12cef43d65784b2559e/Sources/ComplexModule/ElementaryFunctions.swift#L333-L334)

**Comment by stephentyrone** [comment]
Sterbenz' lemma holds for floating-point numbers in any radix, not just radix-2. From this the other comment also follows for decimal (though I guess I could change "bit" to "digit" for clarity.)
