### ISSUE TITLE
Floating point exponent `pow` returns NaN for integer exponents

### ISSUE THREAD

**Issue by PatrickPijnappel** [apple/swift-numerics#221]
Feel free to close if this is intentional, but currently the floating-point version of `pow` returns `NaN` for e.g. `Double.pow(-1, 2.0)`, even though that's not complex. Shouldn't we be checking for `Int(exactly: y) != nil`? This appears to be the behavior of `Darwin.pow(-1, 2.0)`.

```swift
public static func pow(_ x: Double, _ y: Double) -> Double {
    guard x >= 0 else { return .nan }
    return libm_pow(x, y)
}
```

**Comment by xwu** [comment]
This is deliberate:

https://forums.swift.org/t/rejection-of-negative-bases-bug-or-deliberate-design/32082

**Comment by PatrickPijnappel** [comment]
@xwu Ah great that's what I was looking for. Makes sense, thank you.
