### ISSUE TITLE
[FR]: Support Apple Privacy Manifest

### ISSUE THREAD

**Issue by yogashivasankarrisenthilkumar-bounteous** [apple/swift-numerics#287]
Apple introduced Privacy Manifest, in which we need to declare the privacy APIs and data collected.
Resources:
https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

All products we are building are required to adopt this change ,and we have to collect privacy manifests from both internal and external dependencies. 

Does swift-numerics collect any types of data or use any of the privacy APIs mentioned in the links above? If yes, could you please add a privacy manifest file? If no, please let me know on this ticket. Thank you.

**Comment by stephentyrone** [comment]
Just like @lorentey [noted](https://github.com/apple/swift-collections/issues/363) for Swift-Collections, Numerics is not a third-party SDK, certainly isn't on [the list of third party SDKs that require a manifest](https://developer.apple.com/support/third-party-SDK-requirements/), does not use any of the APIs mentioned, and does not collect any user or developer data.

If you receive feedback that such a manifest is necessary, let us know and we'll follow up on this.
