### ISSUE TITLE
Pitch: Add Github `topic` so that more developers find swift-numerics!

### ISSUE THREAD

**Issue by Sajjon** [apple/swift-numerics#37]
Take a look at e.g. the [Tensorflow Github Repo's](https://github.com/tensorflow/tensorflow) "topics" :)

**Comment by Sajjon** [comment]
@stephentyrone adding GitHub topics to thus repo will literally just take a minute but will greatly help with discoverability 👩🏽‍💻🔭

**Comment by stephentyrone** [comment]
SEO is basically the least interesting thing imaginable to me 😂, but I added a few. If there's others that you think would be good to add, put them on this thread and I'll tack them on.

**Comment by Sajjon** [comment]
@stephentyrone Haha :D I figure the more developers who find this, the more contributors, which is always great, no? :) 

What about also adding these topics:
`complex-numbers` ([used by 8 other repos](https://github.com/topics/complex-numbers))
`trigonometry` ([used by 8 other repos](https://github.com/topics/trigonometry))
`sigmoid-function`  ([used by 8 other repos](https://github.com/topics/sigmoid-function))
?

**Comment by Sajjon** [comment]
Looks good, missed `sigmoid-function` though, but not important. I'm closing this issue.
