### ISSUE TITLE
The `real` and `imaginary` properties of `Complex` should be settable

### ISSUE THREAD

**Issue by NevinBR** [apple/swift-numerics#40]
The current implementation of `Complex` has both `real` and `imaginary` as get-only. These properties should have setters.

**Comment by stephentyrone** [comment]
PRs welcome!

**Comment by Wildchild9** [comment]
I just submitted a pull request to add setters for to both the `real` and `imaginary` property on `Complex`.

**Comment by markuswntr** [comment]
> I just submitted a pull request to add setters for to both the `real` and `imaginary` property on `Complex`.

I think this issue can be closed given https://github.com/apple/swift-numerics/pull/43 has been merged.
