### ISSUE TITLE
Naming of `phase` argument label for `Complex`

### ISSUE THREAD

**Issue by NevinBR** [apple/swift-numerics#53]
Currently, the `Complex` type uses the word `phase` in a variety of places.

The technical term for the angle of a complex number is its “argument”, however that word already has a quite different meaning in Swift and programming languages in general, so it would be confusing to use here.

The commonplace, readily-understood term for the angle of a complex number, is, well, its “angle”. There is little to no chance of confusion if we use “angle”.

In contrast, “phase” is far more esoteric, perhaps to the point of jargon. While a mathematician, an electrical engineer, and a quantum physicist (hmm, that reminds me of a joke…) will know what it means, there is a high chance that many programmers in the wider audience will be unfamiliar with the term.

I think it would be most clear to use “angle” instead of “phase” for the `Complex` type.

**Comment by stephentyrone** [comment]
`phase` is certainly more common than `angle` in this use, and definitely more specific (`angle` is used in lots of other contexts). For one example, on the wikipedia page for complex numbers, `phase` appears with exactly this meaning; the closest `angle` comes is "the angle of the radius Oz with the positive real axis".

I'm open to being convinced, but currently weakly in favor of keeping `phase`.

**Comment by NevinBR** [comment]
> `phase` is certainly more common than `angle` in this use

I am not convinced of this.

> and definitely more specific (`angle` is used in lots of other contexts).

Nor of this. Phase is also used in lots of other contexts. For example:

Phases of matter in chemistry
Phases of development in biology
Phase space in dynamical systems
Phases of a project in engineering
Phases of the moon in astronomy
etc.

With “angle”, if the context is even vaguely related to math / physics / engineering, there’s only one meaning.

> For one example, on the wikipedia page for complex numbers, `phase` appears with exactly this meaning; the closest `angle` comes is "the angle of the radius Oz with the positive real axis".

The word “phase” appears 5 times on the Wikipedia page for complex numbers. The word “angle” appears 13 times (searching for “angle” gives 33 results, but 20 of them are for “triangle”). This tells me that when discussing complex numbers, it is much more common to talk about angles than phases.

Similarly, on the Wikipedia page for “Argument (complex analysis)”, the word “phase” appears once and the word “angle” appears 11 times. Notably, the only appearance of “phase” there is a remark that it is sometimes used as a synonym. The entire rest of the article uses “angle”

**Comment by stephentyrone** [comment]
> The word “phase” appears 5 times on the Wikipedia page for complex numbers. The word “angle” appears 13 times

The majority of these are not talking about the argument, though (and when they are, they explicitly say "angle z makes with the real axis" or similar, rather than "angle of z". By contrast, 4/5 uses of "phase" are explicitly talking about "the phase" of a complex value.
