### ISSUE TITLE
Complex division (0, 0) / (0, 0) should return `.infinity`

### ISSUE THREAD

**Issue by NevinBR** [apple/swift-numerics#54]
Currently, dividing `Complex(0, 0)` by itself returns `Complex(0, 0)`, but it should return `.infinity` to represent the undefined result.

**Comment by stephentyrone** [comment]
This should be fixed in rescaledDivide, here:
```
if z.isZero || !w.isFinite { return .zero }
```

**Comment by Wildchild9** [comment]
This issue can be closed, the bug fix has been merged.
