### ISSUE TITLE
Move benchmarks out of tests into their own binary target

### ISSUE THREAD

**Issue by stephentyrone** [apple/swift-numerics#75]
So that we do not have to run tests with `-c release`, and to separate the two more cleanly.

**Comment by stephentyrone** [comment]
This also lets us avoid the Xcode `measure` infrastructure, which offers some nice conveniences, but also isn't totally ideal for our intended use.

**Comment by weissi** [comment]
In SwiftNIO we use a make-shift benchmarking ["framework"](https://github.com/apple/swift-nio/blob/master/Sources/NIOPerformanceTester/main.swift#L22-L58) in [`NIOPerformanceTester`](https://github.com/apple/swift-nio/tree/master/Sources/NIOPerformanceTester).

If this project will create a SwiftPM compatible benchmarking framework, we would like to steal that too :D

**Comment by stephentyrone** [comment]
This is "done" in that the time-consuming tests have been removed. I think the long-term solution I want here is to adopt Karoy's benchmarking setup from collections, but that will require a separate Numerics-Benchmark project; it can't live in Numerics because that will end up giving us layering violations (alternatively, SPM might change how dependency graphs are tracked, which would also provide a solution).
