### ISSUE TITLE
Protocol for algorithms on both real and complex numbers

### ISSUE THREAD

**Issue by NevinBR** [apple/swift-numerics#79]
We should have a protocol that floating-point types as well as `Complex` conform to, which includes multiplication and division. This will enable people to write more useful generic algorithms for those types.

One option is a protocol (perhaps named `Field`) that refines `Numeric` and includes division. Then algorithms could be written against either `Field` or `Field & ElementaryFunctions`.

**Comment by stephentyrone** [comment]
Note that the Field protocol in particular falls out naturally when we add a linear algebra module.

**Comment by NevinBR** [comment]
Will we want the `Real` protocol to refine `Field`?

**Comment by stephentyrone** [comment]
Most likely.

**Comment by stephentyrone** [comment]
https://github.com/apple/swift-numerics/pull/91

**Comment by stephentyrone** [comment]
Merged to master (with the imperfect name "AlgebraicField").
