### ISSUE TITLE
Float16 (half-precision floating-point)

### ISSUE THREAD

**Issue by stephentyrone** [apple/swift-numerics#8]
Implement the IEEE-754 `Float16` type, conforming to `BinaryFloatingPoint`. Use x86 and arm half<->float conversions, and armv8.2 half-precision arithmetic when available.

**Comment by dwaite** [comment]
Would having this type in `swift-numerics` vs stdlib hinder its use as a SIMD type?

**Comment by dwaite** [comment]
For reference: 

swift evolution discussion
https://forums.swift.org/t/add-float16/19370

an implementation in progress (PR)
https://github.com/apple/swift/pull/21738

**Comment by BenLeggiero** [comment]
Can this be closed now?
