### ISSUE TITLE
[Complex] Encode and decode using unkeyedContainer

### ISSUE THREAD

**Issue by benrimmington** [apple/swift-numerics#95]
The encoding would change from `{"x":0,"y":0}` to `[0,0]` in JSON.

[SE-0239][] was originally pitched with CodingKeys, but in a [discussion][] of the implementation, Tony Parker wrote:

> This is one of those cases where I think we should just use two unkeyed values. `ClosedRange` is well defined and I don't think it's likely for it to grow the need for more keys. Same goes for the other `Range` types.

> This would probably also make the encoded range types more parsable by other languages when encoded to JSON.

> ... I feel very strongly that we should prefer a compact representation for fundamental and mathematically-defined types like this.

Instead of the synthesized conformance, we could use the following:

```swift
extension Complex: Decodable where RealType: Decodable {
  public init(from decoder: Decoder) throws {
    var unkeyedContainer = try decoder.unkeyedContainer()
    let x = try unkeyedContainer.decode(RealType.self)
    let y = try unkeyedContainer.decode(RealType.self)
    self.init(x, y)
  }
}

extension Complex: Encodable where RealType: Encodable {
  public func encode(to encoder: Encoder) throws {
    var unkeyedContainer = encoder.unkeyedContainer()
    try unkeyedContainer.encode(x)
    try unkeyedContainer.encode(y)
  }
}
```

[SE-0239]: <https://github.com/apple/swift-evolution/blob/master/proposals/0239-codable-range.md>
[discussion]: <https://github.com/apple/swift/pull/19532#discussion_r220633453>

**Comment by benrimmington** [comment]
Here's a simple test for the [PropertyTests.swift][] file:

```swift
final class PropertyTests: XCTestCase {

  func testCodable<T: Codable & Real>(_ type: T.Type) throws {
    let encoder = JSONEncoder()
    encoder.nonConformingFloatEncodingStrategy = .convertToString(
      positiveInfinity: "inf",
      negativeInfinity: "-inf",
      nan: "nan")

    let decoder = JSONDecoder()
    decoder.nonConformingFloatDecodingStrategy = .convertFromString(
      positiveInfinity: "inf",
      negativeInfinity: "-inf",
      nan: "nan")

    for expected: Complex<T> in [.zero, .one, .i, .infinity] {
      let data = try encoder.encode(expected)
      // print("*** \(String(decoding: data, as: Unicode.UTF8.self)) ***")
      let actual = try decoder.decode(Complex<T>.self, from: data)
      XCTAssertEqual(actual, expected)
    }
  }

  func testCodable() throws {
    try testCodable(Float32.self)
    try testCodable(Float64.self)
    // Float80 doesn't conform to Codable.
  }
}
```

[PropertyTests.swift]: <https://github.com/apple/swift-numerics/blob/7bd29098750f8ad0a09bb3a022320a0ee8322cda/Tests/ComplexTests/PropertyTests.swift>

**Comment by stephentyrone** [comment]
Hi Ben! This makes good sense to me. If you throw up a PR, I'll review.
